name: GitHub Actions After Push Into Develop Branch
on:
  push:
    branches:
      - develop
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      job: [0, 1, 2]
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
           node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        run: npx currents run --parallel --record --key j6XZkxnUlmBUzDo4 --ci-build-id ${{ github.run_id }}
